version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app
permissions:
  - object: /var/www/app
    pattern: "*.sh"
    owner: root
    group: root
    mode: 775
    type:
      - file
hooks:
#  There's no need to stop the application since we can hot reload the configuration.
#  ApplicationStop:
#    - location: scripts/application-stop.sh
  AfterInstall:
    - location: scripts/after-install.sh
  ApplicationStart:
    - location: scripts/application-start.sh
