- name: Add Mysql user
  proxysql_mysql_users:
    login_user:  "{{ proxysql_admin_user }}" 
    login_password: "{{ proxysql_admin_user }}" 
    username: "{{ username_to_add }}"   
    password: "{{ password_to_add }}" 
    default_hostgroup: 10
    transaction_persistent: yes
    max_connections: 10000
    state: present
    load_to_runtime: yes
    save_to_disk: yes
  tags:
  - add_proxysql_user