---
- name: Add ProxySQL users
  include_tasks: add_proxysql_user.yml
  tags:
  - add_proxysql_user

- name: Delete ProxySQL users
  include_tasks: delete_proxysql_user.yml
  tags:
  - delete_proxysql_user

- name: Sync ProxySQL users
  include_tasks: sync_proxysql_users.yml
  tags:
  - sync_proxysql_users

- name: Add ProxySQL MySQL Server
  include_tasks: add_proxysql_mysql_server.yml
  tags:
  - add_proxysql_mysql_server

- name: Delete ProxySQL MySQL Server
  include_tasks: delete_proxysql_mysql_server.yml
  tags:
  - delete_proxysql_mysql_server

- name: Modify variable
  include_tasks: modify_global_variables.yml
  tags:
  - modify_proxysql_variable