- name: Modify global variables
  proxysql_global_variables:
    login_user:  "{{ proxysql_admin_user }}" 
    login_password: "{{ proxysql_admin_password }}" 
    variable: "{{ global_variables }}"
    value: "{{ global_variables_value }}"
    load_to_runtime: True
    save_to_disk: True
  tags:
  - modify_proxysql_variable
