---
- name: proxysql | config | manage rules | rule 1
  proxysql_query_rules:
    login_user: "{{ proxysql_admin_user }}"
    login_password: "{{ proxysql_admin_password }}"
    active: 1
    match_pattern: "{{ proxysql_rule_pattern_select_readers }}" 
    destination_hostgroup: "{{ proxysql_reader_hostgroup_id }}"
    apply: 1

- name: proxysql | config | manage rules | rule 2
  proxysql_query_rules:
    login_user: "{{ proxysql_admin_user }}"
    login_password: "{{ proxysql_admin_password }}"
    active: 1
    match_pattern: "{{ proxysql_rule_pattern_select_for_update_writer }}"
    destination_hostgroup: "{{ proxysql_writer_hostgroup_id }}"
    apply: 1