---
- name: proxysql | syncusers from MySQL master instance to ProxySQL
  command: proxysql-admin --syncusers --server="{{ proxysql_database_writer_hostname }}:{{ proxysql_mysql_port }}" --cluster-username="{{ database_username }}" --cluster-password="{{ database_password }}"

- name: proxysql | update read-only users to reader hostgroup
  command: mysql --socket="{{ proxysql_admin_socket }}" --host="{{ proxysql_admin_bind_address }}" --port="{{ proxysql_port }}" --user="{{ proxysql_admin_user }}" --password="{{ proxysql_admin_password }}" -e 'update mysql_users set default_hostgroup=11 where username like "%-ro-%";load mysql users to runtime; save mysql users to disk;' 
